In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv('Ratings.csv')

In [3]:
data.head()

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2

In [11]:
#Importing the PCA module
from sklearn.decomposition import PCA
pca1 = PCA(svd_solver='randomized', random_state=42)

In [12]:
pca1.fit(data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=42,
    svd_solver='randomized', tol=0.0, whiten=False)

In [18]:
pca.components_

array([[-0.31118649, -0.48101502,  0.35622281, -0.69199674, -0.25696953],
       [ 0.90672615, -0.31113879,  0.25507174, -0.09225738,  0.08641369],
       [-0.12857449, -0.38163517, -0.34923551, -0.16484744,  0.82986931],
       [ 0.1452065 , -0.34290409, -0.79235694, -0.05662208, -0.47989194],
       [-0.20831306, -0.63920934,  0.24134777,  0.69444104, -0.08671783]])

In [17]:
pca1.explained_variance_ratio_.round(2)

array([0.65, 0.15, 0.13, 0.06, 0.  ])

In [3]:
data=pd.read_csv('MyFoodRatings.csv')

In [4]:
data.head()

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0    A        5       5       5         0            0     0      0      0   
1    B        4       4       4         0            0     0      0      0   
2    C        3       3       3         0            0     0      0      0   
3    D        2       2       2         0            0     0      0      0   
4    E        0       0       0         2            2     2      0      0   

   Tempura  
0        0  
1        0  
2        0  
3        0  
4        0

In [8]:
data_1=data.drop('Name',axis=1)

In [9]:
data_1

Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0         5       5       5         0            0     0      0      0   
1         4       4       4         0            0     0      0      0   
2         3       3       3         0            0     0      0      0   
3         2       2       2         0            0     0      0      0   
4         0       0       0         2            2     2      0      0   
5         0       0       0         1            1     1      0      0   
6         0       0       0         5            3     4      0      0   
7         0       0       0         4            4     4      0      0   
8         0       0       0         0            0     0      2      2   
9         0       0       0         0            0     0      1      1   
10        0       0       0         0            0     0      3      4   
11        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [10]:
u, s, vt = np.linalg.svd(data_1, full_matrices=True)

In [11]:
u.shape

(12, 12)

In [12]:
vt.shape

(9, 9)

In [13]:
s

array([1.27279221e+01, 1.05770379e+01, 8.84826058e+00, 1.24205263e+00,
       1.06125858e+00, 4.06927550e-01, 5.43862610e-16, 3.23597471e-16,
       2.65957113e-32])

In [14]:
s.max()

12.727922061357855

In [15]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [16]:
u

array([[-6.80413817e-01,  0.00000000e+00,  0.00000000e+00,
         2.58908743e-33,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  6.83951720e-01, -2.63148402e-01,
         1.45752665e-18,  0.00000000e+00,  0.00000000e+00],
       [-5.44331054e-01,  4.96506831e-17,  3.85856584e-18,
        -1.78352620e-17,  2.48253415e-16,  8.15015983e-17,
        -4.42281885e-01, -2.92767967e-01,  6.46521942e-01,
        -1.62440512e-02,  5.53840102e-02, -3.24881025e-02],
       [-4.08248290e-01,  4.38559108e-33,  3.19773868e-34,
        -7.06645285e-34,  1.21871670e-32,  3.18417792e-33,
        -4.79822791e-17, -6.51972922e-01, -6.38955900e-01,
        -1.00346663e-18,  4.00753524e-18, -1.59750734e-18],
       [-2.72165527e-01, -9.93013661e-17, -7.71713167e-18,
         3.56705241e-17, -4.96506831e-16, -1.63003197e-16,
         8.84563769e-01, -1.46383983e-01,  3.23260971e-01,
         3.24881025e-02, -1.10768020e-01,  6.49762050e-02],
       [ 0.00000000e+00, -3.26217015e-01, -5.1838711

In [18]:
pd.DataFrame(vt)

0         1         2         3         4         5         6  \
0 -0.577350 -0.577350 -0.577350  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000 -0.476163   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.296110   
4 -0.000000 -0.000000 -0.000000  0.653030 -0.755593 -0.051282  0.000000   
5 -0.000000 -0.000000 -0.000000  0.000000  0.000000  0.000000  0.828002   
6  0.000000  0.000000  0.000000 -0.408248 -0.408248  0.816497  0.000000   
7  0.816497 -0.408248 -0.408248  0.000000  0.000000  0.000000  0.000000   
8  0.000000 -0.707107  0.707107  0.000000  0.000000  0.000000  0.000000   

          7         8  
0  0.000000  0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933  
3  0.626381 -0.721087  
4  0.000000  0.000000  
5 -0.544690 -0.133137  
6  0.000000  0.000000  
7  0.000000  0.000000  
8  0.000000  0.000000

In [19]:
data=pd.read_csv('FoodRatings_all_same_5.csv')

In [21]:
data

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         5            5     5      0      0   
5     F        0       0       0         5            5     5      0      0   
6     G        0       0       0         5            5     5      0      0   
7     H        0       0       0         5            5     5      0      0   
8     I        0       0       0         0            0     0      5      5   
9     J        0       0       0         0            0     0      5      5   
10    K        0       0       0         0            0     0      5      5   
11    L        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [22]:
data_1=data.drop('Name',axis=1)

In [23]:
u, s, vt = np.linalg.svd(data_1, full_matrices=True)

In [24]:
s

array([1.73205081e+01, 1.73205081e+01, 1.73205081e+01, 3.92523115e-16,
       2.79802815e-49, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [25]:
data=pd.read_csv('FoodRatings_all_same_5_4_3.csv')

In [26]:
data

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         4            4     4      0      0   
5     F        0       0       0         4            4     4      0      0   
6     G        0       0       0         4            4     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      3      3   
9     J        0       0       0         0            0     0      3      3   
10    K        0       0       0         0            0     0      3      3   
11    L        0       0       0         0            0     0      3      3   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         3  
9         3  
10        3  
11        3

In [27]:
data_1=data.drop('Name',axis=1)
u, s, vt = np.linalg.svd(data_1, full_matrices=True)

In [28]:
s

array([1.73205081e+01, 1.38564065e+01, 1.03923048e+01, 3.92523115e-16,
       2.79802815e-49, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [29]:
# Importing Pandas and NumPy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
# Importing all datasets
churn_data = pd.read_csv("churn_data.csv")
customer_data = pd.read_csv("customer_data.csv")
internet_data = pd.read_csv("internet_data.csv")

In [31]:
print(len(churn_data))
print(len(customer_data))
print(len(internet_data))

7043
7043
7043


In [32]:
df_1 = pd.merge(churn_data, customer_data, how='inner', on='customerID')
telecom = pd.merge(df_1, internet_data, how='inner', on='customerID')

In [33]:
telecom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
dtypes: float64(1), int64(2), obj

In [34]:
# Converting Yes to 1 and No to 0
telecom['PhoneService'] = telecom['PhoneService'].map({'Yes': 1, 'No': 0})
telecom['PaperlessBilling'] = telecom['PaperlessBilling'].map({'Yes': 1, 'No': 0})
telecom['Churn'] = telecom['Churn'].map({'Yes': 1, 'No': 0})
telecom['Partner'] = telecom['Partner'].map({'Yes': 1, 'No': 0})
telecom['Dependents'] = telecom['Dependents'].map({'Yes': 1, 'No': 0})

In [35]:
# Creating a dummy variable for the variable 'Contract' and dropping the first one.
cont = pd.get_dummies(telecom['Contract'],prefix='Contract',drop_first=True)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,cont],axis=1)

# Creating a dummy variable for the variable 'PaymentMethod' and dropping the first one.
pm = pd.get_dummies(telecom['PaymentMethod'],prefix='PaymentMethod',drop_first=True)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,pm],axis=1)

# Creating a dummy variable for the variable 'gender' and dropping the first one.
gen = pd.get_dummies(telecom['gender'],prefix='gender',drop_first=True)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,gen],axis=1)

# Creating a dummy variable for the variable 'MultipleLines' and dropping the first one.
ml = pd.get_dummies(telecom['MultipleLines'],prefix='MultipleLines')
#  dropping MultipleLines_No phone service column
ml1 = ml.drop(['MultipleLines_No phone service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,ml1],axis=1)

# Creating a dummy variable for the variable 'InternetService' and dropping the first one.
iser = pd.get_dummies(telecom['InternetService'],prefix='InternetService',drop_first=True)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,iser],axis=1)

# Creating a dummy variable for the variable 'OnlineSecurity'.
os = pd.get_dummies(telecom['OnlineSecurity'],prefix='OnlineSecurity')
os1= os.drop(['OnlineSecurity_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,os1],axis=1)

# Creating a dummy variable for the variable 'OnlineBackup'.
ob =pd.get_dummies(telecom['OnlineBackup'],prefix='OnlineBackup')
ob1 =ob.drop(['OnlineBackup_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,ob1],axis=1)

# Creating a dummy variable for the variable 'DeviceProtection'. 
dp =pd.get_dummies(telecom['DeviceProtection'],prefix='DeviceProtection')
dp1 = dp.drop(['DeviceProtection_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,dp1],axis=1)

# Creating a dummy variable for the variable 'TechSupport'. 
ts =pd.get_dummies(telecom['TechSupport'],prefix='TechSupport')
ts1 = ts.drop(['TechSupport_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,ts1],axis=1)

# Creating a dummy variable for the variable 'StreamingTV'.
st =pd.get_dummies(telecom['StreamingTV'],prefix='StreamingTV')
st1 = st.drop(['StreamingTV_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,st1],axis=1)

# Creating a dummy variable for the variable 'StreamingMovies'. 
sm =pd.get_dummies(telecom['StreamingMovies'],prefix='StreamingMovies')
sm1 = sm.drop(['StreamingMovies_No internet service'],1)
#Adding the results to the master dataframe
telecom = pd.concat([telecom,sm1],axis=1)

In [36]:
telecom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 43 columns):
customerID                               7043 non-null object
tenure                                   7043 non-null int64
PhoneService                             7043 non-null int64
Contract                                 7043 non-null object
PaperlessBilling                         7043 non-null int64
PaymentMethod                            7043 non-null object
MonthlyCharges                           7043 non-null float64
TotalCharges                             7043 non-null object
Churn                                    7043 non-null int64
gender                                   7043 non-null object
SeniorCitizen                            7043 non-null int64
Partner                                  7043 non-null int64
Dependents                               7043 non-null int64
MultipleLines                            7043 non-null object
InternetService                

In [37]:
# We have created dummies for the below variables, so we can drop them
telecom = telecom.drop(['Contract','PaymentMethod','gender','MultipleLines','InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies'], 1)

In [38]:
telecom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 0 to 7042
Data columns (total 32 columns):
customerID                               7043 non-null object
tenure                                   7043 non-null int64
PhoneService                             7043 non-null int64
PaperlessBilling                         7043 non-null int64
MonthlyCharges                           7043 non-null float64
TotalCharges                             7043 non-null object
Churn                                    7043 non-null int64
SeniorCitizen                            7043 non-null int64
Partner                                  7043 non-null int64
Dependents                               7043 non-null int64
Contract_One year                        7043 non-null uint8
Contract_Two year                        7043 non-null uint8
PaymentMethod_Credit card (automatic)    7043 non-null uint8
PaymentMethod_Electronic check           7043 non-null uint8
PaymentMethod_Mailed check         

In [45]:
#telecom['TotalCharges'] =telecom['TotalCharges'].astype(dtype=np.float64)
telecom['TotalCharges'] = (telecom['TotalCharges'].str.split()).apply(lambda x: float(x[0].replace(',', '')))


IndexError: list index out of range

In [ ]:
df[column] = (df[column].str.split()).apply(lambda x: float(x[0].replace(',', '')))